name: Rekam Cloud TikTok

on:
  workflow_dispatch:

jobs:
  record_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Apps & yt-dlp
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg rclone
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Setup GDrive
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_DATA }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Rekam Live Test (weexlance - 2 Menit)
        continue-on-error: true
        run: |
          yt-dlp --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" \
                 --referer "https://www.tiktok.com/" \
                 --downloader ffmpeg \
                 --downloader-args "ffmpeg:-t 120" \
                 -o "raw_weexlance.ts" \
                 "https://www.tiktok.com/@weexlance/live" || true

          if [ -f "raw_weexlance.ts" ] && [ -s "raw_weexlance.ts" ]; then
            ffmpeg -y -i "raw_weexlance.ts" -c copy -movflags +faststart "rekaman_weexlance_$(date +'%Y%m%d_%H%M%S').mp4"
            rm "raw_weexlance.ts"
          fi

      - name: Upload ke GDrive
        if: always()
        run: |
          rclone copy ./ gdrive:TikTok_Replays --include "rekaman_*.mp4" --progress
