name: Rekam Cloud TikTok

on:
  workflow_dispatch:

jobs:
  record_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Apps & Streamlink
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg rclone
          pip install --upgrade streamlink

      - name: Setup GDrive
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_DATA }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Rekam Live Test (weexlance - 2 Menit)
        continue-on-error: true
        run: |
          timeout 120s streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" \
                     --http-header "Referer=https://www.tiktok.com/" \
                     "https://www.tiktok.com/@weexlance/live" best \
                     -o "temp_weexlance.mkv" --force || true

          if [ -f "temp_weexlance.mkv" ] && [ -s "temp_weexlance.mkv" ]; then
            ffmpeg -y -i "temp_weexlance.mkv" -c copy -movflags +faststart "rekaman_weexlance_$(date +'%Y%m%d_%H%M%S').mp4"
            rm "temp_weexlance.mkv"
          fi

      - name: Upload ke GDrive
        if: always()
        run: |
          rclone copy ./ gdrive:TikTok_Replays --include "*.mp4" --progress
