name: 🔴 Rekam Tes Full Live TikTok

on:
  workflow_dispatch:

jobs:
  record_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Apps & Streamlink
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg rclone
          pip install --upgrade streamlink

      - name: Setup GDrive
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_DATA }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Rekam Live nanaaheni_
        continue-on-error: true
        run: |
          streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" \
            --http-header "Referer=https://www.tiktok.com/" \
            --retry-streams 5 \
            --retry-max 10 \
            "https://www.tiktok.com/@nanaaheni_/live" h264_hd,h264_best,720p,best \
            -o "raw_nanaaheni.ts" --force || true

          if [ -f "raw_nanaaheni.ts" ] && [ -s "raw_nanaaheni.ts" ]; then
            ffmpeg -y -i "raw_nanaaheni.ts" -c copy -movflags +faststart "rekaman_nanaaheni_$(date +'%Y%m%d_%H%M%S').mp4"
            rm "raw_nanaaheni.ts"
          fi

      - name: Rekam Live nnaaheni
        continue-on-error: true
        run: |
          streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" \
            --http-header "Referer=https://www.tiktok.com/" \
            --retry-streams 5 \
            --retry-max 10 \
            "https://www.tiktok.com/@nnaaheni/live" h264_hd,h264_best,720p,best \
            -o "raw_nnaaheni.ts" --force || true

          if [ -f "raw_nnaaheni.ts" ] && [ -s "raw_nnaaheni.ts" ]; then
            ffmpeg -y -i "raw_nnaaheni.ts" -c copy -movflags +faststart "rekaman_nnaaheni_$(date +'%Y%m%d_%H%M%S').mp4"
            rm "raw_nnaaheni.ts"
          fi

      - name: Upload ke GDrive
        if: always()
        run: |
          mkdir -p build_output
          mv rekaman_*.mp4 build_output/ 2>/dev/null || true
          
          if [ -d "build_output" ] && [ "$(ls -A build_output)" ]; then
            rclone copy build_output/ gdrive:TikTok_Replays --progress
          fi
