name: 2️⃣ Rekam Test 2 Live TikTok

on:
  workflow_dispatch:

jobs:
  record_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Apps & Streamlink
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg rclone
          pip install --upgrade streamlink

      - name: Setup GDrive
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_DATA }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Rekam Live ranngusion__ (Test Limit)
        continue-on-error: true
        run: |
          timeout 180 streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" \
            --http-header "Referer=https://www.tiktok.com/" \
            --retry-streams 9999 \
            --retry-max 0 \
            "https://www.tiktok.com/@ranngusion__/live" h264_hd,h264_best,720p,best \
            -o "raw_ranngusion.ts" --force || true

          if [ -f "raw_ranngusion.ts" ] && [ -s "raw_ranngusion.ts" ]; then
            ffmpeg -y -i "raw_ranngusion.ts" -c copy -movflags +faststart "rekaman_ranngusion_$(date +'%Y%m%d_%H%M%S').mp4"
            rm "raw_ranngusion.ts"
          fi

      - name: Upload ke GDrive
        if: always()
        run: |
          mkdir -p build_output
          mv rekaman_*.mp4 build_output/ 2>/dev/null || true
          
          if [ -d "build_output" ] && [ "$(ls -A build_output)" ]; then
            rclone copy build_output/ gdrive:TikTok_Replays --progress
          fi
