name: 🔴 Rekam Tes TikTok

on:
  workflow_dispatch:

jobs:
  record_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yt-dlp & rclone
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg rclone
          # Menginstall yt-dlp versi terbaru yang tahan blokir TikTok
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Setup GDrive
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_DATA }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Rekam Live cipuyyy221 (Anti Blokir)
        continue-on-error: true
        run: |
          echo "Merekam cipuyyy221 selama 5 menit..."
          
          # timeout 300s (5 menit) akan menghentikan yt-dlp, dan yt-dlp otomatis menyimpan file MP4 dengan sempurna
          timeout 300s yt-dlp "https://www.tiktok.com/@cipuyyy221/live" -o "rekaman_cipuyyy221_$(date +'%Y%m%d_%H%M%S').mp4" || true

      - name: Upload ke GDrive
        if: always()
        run: |
          mkdir -p build_output
          mv rekaman_*.mp4 build_output/ 2>/dev/null || true
          if [ -d "build_output" ] && [ "$(ls -A build_output)" ]; then
            rclone copy build_output/ gdrive:TikTok_Replays --progress
          fi
